services:
  gsender2mqtt:
    build: .
    restart: unless-stopped
    environment:
      - SERVERURL=${SERVERURL:-http://localhost:8000}
      - GRBLHALIPADDRESS=${GRBLHALIPADDRESS:-}
      - MQTTSERVER=${MQTTSERVER:-localhost}
      - MQTTPORT=${MQTTPORT:-1883}
      - MQTTUSERNAME=${MQTTUSERNAME:-}
      - MQTTPASSWORD=${MQTTPASSWORD:-}
      - MQTTTOPIC=${MQTTTOPIC:-gsender}
      - MQTT_EMIT_TOPIC=${MQTT_EMIT_TOPIC:-gsender/emit}
      - MQTTCLIENTID=${MQTTCLIENTID:-gsender2mqtt}
      - RETRYDELAY=${RETRYDELAY:-60000}